### ISSUE TITLE
Console error Purpur 1.21.1 (plugin does not work) 

### ISSUE THREAD

**Issue by KyloSoot** [ssquadteam/Geyser-Anvil-Fix#3]
[09:48:17 INFO]: [Geyser-Spigot] ******************************************
[09:48:17 INFO]: [Geyser-Spigot] 
[09:48:17 INFO]: [Geyser-Spigot] Loading Geyser version 2.4.4-b694 (git-master-e7ecb55)
[09:48:17 INFO]: [Geyser-Spigot] 
[09:48:17 INFO]: [Geyser-Spigot] ******************************************
[09:48:18 INFO]: [Geyser-Spigot] Registered 1 custom items
[09:48:21 ERROR]: [org.geysermc.geyser.event.GeyserEventBus] An exception occurred while executing event GeyserLoadResourcePacksEvent for subscriber org.geysermc.geyser.event.GeyserEventSubscriber
java.lang.IllegalArgumentException: The embedded resource 'geyseranvilfix-Pack.mcpack' cannot be found in plugins/.paper-remapped/Geyser Anvil Fix 1.0.0.jar
        at org.bukkit.plugin.java.JavaPlugin.saveResource(JavaPlugin.java:215) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at Geyser Anvil Fix 1.0.0.jar/net.ssquadteam.geyseranvilfix.hooks.GeyserEvents.onGeyserLoadResourcePacks(GeyserEvents.java:31) ~[Geyser Anvil Fix 1.0.0.jar:?]
        at Geyser-Spigot.jar/org.geysermc.event.subscribe.impl.SubscriberImpl.invoke(SubscriberImpl.java:75) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.event.bus.impl.BaseBusImpl.fireSilently(BaseBusImpl.java:201) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.event.bus.impl.OwnedEventBusImpl.fireSilently(OwnedEventBusImpl.java:41) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.event.bus.impl.BaseBusImpl.fire(BaseBusImpl.java:180) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.event.bus.impl.OwnedEventBusImpl.fire(OwnedEventBusImpl.java:41) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.geyser.registry.loader.ResourcePackLoader.load(ResourcePackLoader.java:98) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.geyser.registry.loader.ResourcePackLoader.load(ResourcePackLoader.java:57) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.geyser.registry.DeferredRegistry.lambda$new$2(DeferredRegistry.java:64) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.geyser.registry.DeferredRegistry.load(DeferredRegistry.java:111) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.geyser.GeyserImpl.startInstance(GeyserImpl.java:300) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.geyser.GeyserImpl.initialize(GeyserImpl.java:265) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.geyser.GeyserImpl.start(GeyserImpl.java:870) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin.onGeyserEnable(GeyserSpigotPlugin.java:236) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin$1.onServerLoaded(GeyserSpigotPlugin.java:220) ~[Geyser-Spigot.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:44) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2328-d49ca07]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:764) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by KyloSoot** [comment]
No files were generated in the plugin folder (only config.yml)

**Comment by ssquadteam** [comment]
[Could you try the latest version?](https://github.com/ssquadteam/Geyser-Anvil-Fix/releases/tag/1.0.1)

**Comment by KyloSoot** [comment]
Fixed. tysm
